FROM ubuntu:24.04

# Install Python
RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the input data into the container
COPY users.json /app/users.json
